_BASE_: "../../../detectron2/configs/COCO-PanopticSegmentation/Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_101_3x/139514519/model_final_cafdb1.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000